In [1]:
import re
import string
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from bs4 import BeautifulSoup
from collections import Counter
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\MAHARJANA\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
df = pd.read_csv('Airline Review Dataset.csv')

In [3]:
df.shape

(23171, 20)

In [4]:
df.head(10)

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,NaN,Solo Leisure,Economy Class,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,Solo Leisure,Economy Class,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
5,5,Adria Airways,1,"""Had very bad experience""",17th September 2019,True,Had very bad experience with rerouted and ca...,CR 900,Couple Leisure,Economy Class,Sarajevo to Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
6,6,Adria Airways,1,"""worse than the budget airlines""",6th September 2019,False,"Ljubljana to Zürich. Firstly, Ljubljana airp...",NaN,Business,Economy Class,Ljubljana to Zürich,September 2019,1.0,1.0,1.0,1.0,NaN,NaN,1.0,no
7,7,Adria Airways,1,"""book another company""",24th August 2019,False,"First of all, I am not complaining about a s...",Bombardier CRJ,Solo Leisure,Economy Class,Timisoara to Munich,August 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
8,8,Adria Airways,1,"""combined two flights""",6th August 2019,True,Worst Airline ever! They combined two flight...,NaN,Solo Leisure,Economy Class,Pristina to Zürich via Ljubliana,August 2019,1.0,2.0,1.0,1.0,1.0,1.0,1.0,no
9,9,Adria Airways,8,"""the crew was nice""",12th October 2018,True,Ljubljana to Munich. The homebase airport of ...,NaN,Family Leisure,Economy Class,Ljubljana to Munich,October 2018,4.0,4.0,3.0,5.0,NaN,NaN,5.0,yes

In [5]:
df['Review'][202]

'  Aer Lingus is a sad excuse for an airline. Not a single of our four flights was on time. We were almost twelve hours late to Paris and had to sit in the Dublin airport all day. There were no employees available to discuss flight details or compensation for delays. The flights also either said they had Wi-Fi but didn’t, or just said flat out they don’t have Wi-Fi. Disastrous airline and I will never fly with them again. Steer clear.'

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23171 entries, 0 to 23170
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              23171 non-null  int64
 1   Airline Name            23171 non-null  object
 2   Overall_Rating          23171 non-null  object
 3   Review_Title            23171 non-null  object
 4   Review Date             23171 non-null  object
 5   Verified                23171 non-null  bool
 6   Review                  23171 non-null  object
 7   Aircraft                7129 non-null   object
 8   Type Of Traveller       19433 non-null  object
 9   Seat Type               22075 non-null  object
 10  Route                   19343 non-null  object
 11  Date Flown              19417 non-null  object
 12  Seat Comfort            19016 non-null  float64
 13  Cabin Staff Service     18911 non-null  float64
 14  Food & Beverages        14500 non-null  float64
 15  Ground Service          18378 non-null  float64
 16  Inflight Entertainment  10829 non-null  float64
 17  Wifi & Connectivity     5920 non-null   float64
 18  Value For Money         22105 non-null  float64
 19  Recommended             23171 non-null  object
dtypes: bool(1), float64(7), int64(1), object(11)
memory usage: 3.4+ MB

In [7]:
# Extract duplicates based on 'Airline Name' and 'Review' columns
duplicates = df[df.duplicated(subset=['Airline Name', 'Review'], keep=False)]
print(duplicates)

       Unnamed: 0             Airline Name Overall_Rating  \
1774         1774            Air Greenland              n
1775         1775            Air Greenland              n
3840         3840          Alaska Airlines              1
3841         3841          Alaska Airlines              1
7032         7032  China Southern Airlines              8
...           ...                      ...            ...
16645       16645              Ravn Alaska              4
16646       16646              Ravn Alaska              5
16647       16647              Ravn Alaska              6
21131       21131                 Tunisair              2
21132       21132                 Tunisair              9

                                   Review_Title         Review Date  Verified  \
1774              Air Greenland customer review   18th October 2007     False
1775              Air Greenland customer review       10th May 2007     False
3840               "Not a great airline at all"   30th January 2023      True
3841   "flight attendants did the bare minimum"   30th January 2023     False
7032           "happily fly this airline again"  31st December 2022      True
...                                         ...                 ...       ...
16645               "never be using Ravn again"  21st December 2015     False
16646                       "was never on time"  20th November 2015     False
16647               Ravn Alaska customer review     27th March 2008     False
21131                  Tunisair customer review      26th July 2012     False
21132                  Tunisair customer review      9th April 2012     False

                                                  Review           Aircraft  \
1774   I used Air Greenland on a trip from Copenhagen...                NaN
1775   I used Air Greenland on a trip from Copenhagen...                NaN
3840     Terrible attitude from the lady at 11am at g...     Boeing 737-900
3841     Terrible attitude from the lady at 11am at g...     Boeing 737-900
7032     Very attentive staff at airport check in and...                NaN
...                                                  ...                ...
16645  Ravn Alaska is so frustrating. First off, your...  Beechcraft B1900D
16646  I have flown out of Homer 4 times this year to...                NaN
16647  ANC-FAI-ANC Economy Open Seating. Check in was...                NaN
21131  LHR-TUN return to LHR. Aircraft was A320 on bo...                NaN
21132  LHR-TUN return to LHR. Aircraft was A320 on bo...                NaN

      Type Of Traveller      Seat Type                    Route  \
1774                NaN            NaN                      NaN
1775                NaN            NaN                      NaN
3840     Family Leisure  Economy Class  San Francisco to Newark
3841     Family Leisure  Economy Class  San Francisco to Newark
7032       Solo Leisure  Economy Class       Guangzhou to Paris
...                 ...            ...                      ...
16645    Couple Leisure  Economy Class   Fairbanks to Anchorage
16646    Couple Leisure  Economy Class       Homer to Anchorage
16647      Solo Leisure  Economy Class                      NaN
21131               NaN  Economy Class                      NaN
21132               NaN  Economy Class                      NaN

          Date Flown  Seat Comfort  Cabin Staff Service  Food & Beverages  \
1774             NaN           NaN                  NaN               NaN
1775             NaN           NaN                  NaN               NaN
3840    January 2023           1.0                  1.0               1.0
3841    January 2023           1.0                  1.0               1.0
7032   December 2022           2.0                  4.0               3.0
...              ...           ...                  ...               ...
16645  December 2015           1.0                  3.0               3.0
16646  November 2015           4.0                  3.0               NaN
16647            NaN           3.0                  4.0               NaN
21131            NaN           NaN                  NaN               NaN
21132            NaN           NaN                  NaN               NaN

       Ground Service  Inflight Entertainment  Wifi & Connectivity  \
1774              NaN                     NaN                  NaN
1775              NaN                     NaN                  NaN
3840              1.0                     1.0                  1.0
3841              1.0                     1.0                  1.0
7032              4.0                     3.0                  NaN
...               ...                     ...                  ...
16645             1.0                     1.0                  1.0
16646             3.0                     NaN                  NaN
16647             3.0                     NaN                  NaN
21131             NaN                     NaN                  NaN
21132             NaN                     NaN                  NaN

       Value For Money Recommended
1774               NaN          no
1775               NaN          no
3840               1.0          no
3841               1.0          no
7032               4.0         yes
...                ...         ...
16645              2.0          no
16646              2.0         yes
16647              4.0         yes
21131              1.0          no
21132              4.0         yes

[250 rows x 20 columns]

In [8]:
df = df.drop_duplicates(subset=['Airline Name', 'Review'])

In [9]:
df.shape

(23046, 20)

In [10]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def preprocess(documents):
    processed_docs = []
    for doc in documents:
        text = re.sub(r'[^a-zA-Z\s]', '', doc) #Remove numbers and special characters
        tokens = text.lower().split()
        lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens]
        processed_docs.append(" ".join(lemmatized_tokens))
    return processed_docs

df['preprocessed_review'] = preprocess(df['Review'])

In [11]:
df.head()

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,...,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended,preprocessed_review
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,NaN,Solo Leisure,Economy Class,...,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes,moroni to moheli turned out to be a pretty dec...
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,...,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no,moroni to anjouan it is a very small airline m...
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,...,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no,anjouan to dzaoudzi a very small airline and t...
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,Solo Leisure,Economy Class,...,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no,please do a favor yourself and do not fly with...
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,Couple Leisure,Economy Class,...,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no,do not book a flight with this airline my frie...

In [12]:
# Delete redundant columns
df.drop(columns=["Unnamed: 0", "Review_Title", "Review Date", "Verified", "Aircraft", "Type Of Traveller", "Route", "Date Flown"], inplace=True)

In [13]:
df.head(10)

,Airline Name,Overall_Rating,Review,Seat Type,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended,preprocessed_review
0,AB Aviation,9,Moroni to Moheli. Turned out to be a pretty ...,Economy Class,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes,moroni to moheli turned out to be a pretty dec...
1,AB Aviation,1,Moroni to Anjouan. It is a very small airline...,Economy Class,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no,moroni to anjouan it is a very small airline m...
2,AB Aviation,1,Anjouan to Dzaoudzi. A very small airline an...,Economy Class,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no,anjouan to dzaoudzi a very small airline and t...
3,Adria Airways,1,Please do a favor yourself and do not fly wi...,Economy Class,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no,please do a favor yourself and do not fly with...
4,Adria Airways,1,Do not book a flight with this airline! My fr...,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no,do not book a flight with this airline my frie...
5,Adria Airways,1,Had very bad experience with rerouted and ca...,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no,had very bad experience with rerouted and canc...
6,Adria Airways,1,"Ljubljana to Zürich. Firstly, Ljubljana airp...",Economy Class,1.0,1.0,1.0,1.0,NaN,NaN,1.0,no,ljubljana to zrich firstly ljubljana airport i...
7,Adria Airways,1,"First of all, I am not complaining about a s...",Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no,first of all i am not complaining about a spec...
8,Adria Airways,1,Worst Airline ever! They combined two flight...,Economy Class,1.0,2.0,1.0,1.0,1.0,1.0,1.0,no,worst airline ever they combined two flight to...
9,Adria Airways,8,Ljubljana to Munich. The homebase airport of ...,Economy Class,4.0,4.0,3.0,5.0,NaN,NaN,5.0,yes,ljubljana to munich the homebase airport of ad...

In [14]:
df.isnull().sum()

Airline Name                  0
Overall_Rating                0
Review                        0
Seat Type                   988
Seat Comfort               4042
Cabin Staff Service        4147
Food & Beverages           8553
Ground Service             4680
Inflight Entertainment    12222
Wifi & Connectivity       17129
Value For Money             958
Recommended                   0
preprocessed_review           0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23046 entries, 0 to 23170
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airline Name            23046 non-null  object
 1   Overall_Rating          23046 non-null  object
 2   Review                  23046 non-null  object
 3   Seat Type               22058 non-null  object
 4   Seat Comfort            19004 non-null  float64
 5   Cabin Staff Service     18899 non-null  float64
 6   Food & Beverages        14493 non-null  float64
 7   Ground Service          18366 non-null  float64
 8   Inflight Entertainment  10824 non-null  float64
 9   Wifi & Connectivity     5917 non-null   float64
 10  Value For Money         22088 non-null  float64
 11  Recommended             23046 non-null  object
 12  preprocessed_review     23046 non-null  object
dtypes: float64(7), object(6)
memory usage: 2.5+ MB

In [16]:
# Converting String Values to Numbers
df["Overall_Rating"] = pd.to_numeric(df["Overall_Rating"], errors='coerce')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23046 entries, 0 to 23170
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airline Name            23046 non-null  object
 1   Overall_Rating          22298 non-null  float64
 2   Review                  23046 non-null  object
 3   Seat Type               22058 non-null  object
 4   Seat Comfort            19004 non-null  float64
 5   Cabin Staff Service     18899 non-null  float64
 6   Food & Beverages        14493 non-null  float64
 7   Ground Service          18366 non-null  float64
 8   Inflight Entertainment  10824 non-null  float64
 9   Wifi & Connectivity     5917 non-null   float64
 10  Value For Money         22088 non-null  float64
 11  Recommended             23046 non-null  object
 12  preprocessed_review     23046 non-null  object
dtypes: float64(8), object(5)
memory usage: 2.5+ MB

In [18]:
df.to_csv('Preprocessed Data.csv', index=False)